/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package basee_de_donnee;
import Appllication.BDD;
import Appllication.ResultSetTableModel;
import Appllication.parameter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Valtsua
 */
public class journalier extends javax.swing.JInternalFrame {

    Connecter con=new Connecter();
       Statement stm;
       ResultSet Rs;
       DefaultTableModel model=new  DefaultTableModel();
       ResultSet rs;
    BDD db;
    /**
     * Creates new form journalier
     */
    public journalier() {
        db = new BDD(new parameter().HOST_DB, new parameter().USERNAME_DB, new parameter().PASSWORD_DB, 
                 new parameter().IPHOST, new parameter().PORT);
        initComponents();
        remove ();
        inporter();
         model.addColumn("Nom");
        model.addColumn("recette");
          try{
          stm=con.obtenirconnexion().createStatement();
          ResultSet Rs=stm.executeQuery("select NomCaisse,sum(subtotal) as recette from ventes where date='"+cachier.jLabel23.getText()+"'");
          while(Rs.next()){
           model.addRow(new Object[]{Rs.getString("NomCaisse"),Rs.getString("recette")});
          }
        } catch(Exception e){System.err.println(e);}
        listecaisse2.setModel(model);
    }
    
    void remove (){
      putClientProperty("cli.isPalette",Boolean.TRUE);
      getRootPane().setWindowDecorationStyle(JRootPane.NONE);
      ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
      this.setBorder(null);
    }
     public void inporter() {
       String colon[] = {"num_vente","CodeProduit","Designation", "prixUnique","NomCaisse","date","qqt","subtotal"};
         rs = db.fcSelectCommand(colon, "ventes", "date='" + cachier.jLabel23.getText() + "'");
        listecaisse2.setModel(new ResultSetTableModel(rs));
        
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listecaisse2 = new javax.swing.JTable();

        listecaisse2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listecaisse2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listecaisse2;
    // End of variables declaration//GEN-END:variables
}
